# Custom Language File for Launcher Customizer

[ejs.app]
title = "Cobblemon Vilinha"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "https://x.com/CobbleVilinha"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/57BNd3wZpR"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BEM VINDO AO COBBLEMON VILINHA"
welcomeDescription = "COBBLEMON VILINHA É UM SERVIDOR NÃO COMPETITIVO QUE TEM COMO OBJETIVO CRIAR UMA COMUNIDADE AMIGÁVEL E ÚNICA EM UM MUNDO POKEMON RP."
welcomeDescCTA = "SÓ MAIS ALGUNS CLIQUES PARA ENTRAR NO MUNDO DE VILINHA"
